
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const x = 1
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      {
        alert("HOLA MUNDO")
        
      }
      </body>
    </html>
  );
}
